In [33]:
import os
import numpy as np
import pandas as pd
from collections import Counter
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from collections import Counter
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, plot_confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

In [34]:
#Naming directories
train_dir = 'train-mails/'
test_dir = 'test-mails/'

In [35]:
#Saving path to all mails in 'emails'
emails = [os.path.join(train_dir,f) for f in os.listdir(train_dir)]

In [36]:
#Display 'emails'
emails.sort()
emails

['train-mails/3-1msg1.txt',
 'train-mails/3-1msg2.txt',
 'train-mails/3-1msg3.txt',
 'train-mails/3-375msg1.txt',
 'train-mails/3-378msg1.txt',
 'train-mails/3-378msg2.txt',
 'train-mails/3-378msg3.txt',
 'train-mails/3-378msg4.txt',
 'train-mails/3-378msg5.txt',
 'train-mails/3-379msg1.txt',
 'train-mails/3-379msg2.txt',
 'train-mails/3-379msg3.txt',
 'train-mails/3-380msg1.txt',
 'train-mails/3-380msg2.txt',
 'train-mails/3-380msg3.txt',
 'train-mails/3-380msg4.txt',
 'train-mails/3-380msg5.txt',
 'train-mails/3-380msg6.txt',
 'train-mails/3-380msg7.txt',
 'train-mails/3-383msg0.txt',
 'train-mails/3-383msg1.txt',
 'train-mails/3-384msg0.txt',
 'train-mails/3-384msg1.txt',
 'train-mails/3-384msg2.txt',
 'train-mails/3-384msg3.txt',
 'train-mails/3-385msg1.txt',
 'train-mails/3-385msg2.txt',
 'train-mails/3-385msg3.txt',
 'train-mails/3-387msg0.txt',
 'train-mails/3-387msg1.txt',
 'train-mails/3-387msg2.txt',
 'train-mails/3-388msg1.txt',
 'train-mails/3-389msg1.txt',
 'train-mails/3-

In [37]:
#Storing data in array
all_words = []
for mail in emails:
    with open(mail) as m:
        for i, line in enumerate(m):
            if i==2:
                words = line.split()
                all_words += words

In [38]:
#Dict to store all words and their freq
from collections import Counter
dictionary = Counter(all_words)

In [39]:
#Display 'dictionary'
dictionary

Counter({'>': 1605,
         'deat': 50,
         ':': 5011,
         'sun': 17,
         ',': 18338,
         '15': 208,
         'dec': 18,
         '91': 4,
         '2': 866,
         '25': 134,
         'est': 21,
         'michael': 36,
         '<': 69,
         'mmorse': 1,
         '@': 752,
         'vm1': 2,
         '.': 28559,
         'yorku': 1,
         'ca': 126,
         'subject': 209,
         're': 190,
         '864': 1,
         'query': 57,
         'wlodek': 1,
         'zadrozny': 1,
         'ask': 206,
         '"': 4410,
         'anything': 93,
         'interest': 362,
         'construction': 74,
         's': 576,
         'np': 27,
         'second': 132,
         'much': 318,
         'relate': 77,
         'consider': 91,
         'form': 380,
         'discuss': 49,
         'list': 935,
         'late': 37,
         'reduplication': 54,
         '?': 1102,
         'logical': 13,
         'sense': 36,
         'john': 109,
         'mcnamara': 3,
 

In [40]:
#Removing stop words
list_to_remove = list(dictionary.keys())
for item in list_to_remove:
    if item.isalpha() == False:
        del dictionary[item]
    elif len(item) == 1:
        del dictionary[item]

In [41]:
#Filtering out less common words with less freq
dictionary = dictionary.most_common(3000)

In [42]:
#Display filtered 'dictionary'
dictionary

[('order', 1414),
 ('address', 1293),
 ('report', 1216),
 ('mail', 1127),
 ('send', 1079),
 ('language', 1072),
 ('email', 1051),
 ('program', 1001),
 ('our', 987),
 ('list', 935),
 ('one', 917),
 ('name', 878),
 ('receive', 826),
 ('money', 788),
 ('free', 762),
 ('work', 755),
 ('information', 677),
 ('business', 654),
 ('please', 652),
 ('university', 595),
 ('us', 564),
 ('day', 556),
 ('follow', 544),
 ('internet', 520),
 ('over', 511),
 ('http', 479),
 ('check', 472),
 ('call', 469),
 ('each', 466),
 ('include', 452),
 ('com', 448),
 ('linguistic', 442),
 ('number', 423),
 ('want', 420),
 ('letter', 419),
 ('need', 418),
 ('many', 412),
 ('here', 397),
 ('market', 395),
 ('start', 390),
 ('even', 386),
 ('fax', 383),
 ('form', 380),
 ('most', 377),
 ('first', 373),
 ('web', 366),
 ('service', 363),
 ('interest', 362),
 ('software', 352),
 ('remove', 349),
 ('read', 347),
 ('those', 345),
 ('week', 344),
 ('every', 332),
 ('credit', 329),
 ('ll', 326),
 ('site', 320),
 ('much', 31

In [43]:
def make_vocabulary(train_dir):
    emails = [os.path.join(train_dir,f) for f in os.listdir(train_dir)]
    all_words = []
    for mail in emails:
        with open(mail) as m:
            for i, line in enumerate(m):
                if i==2:
                    words = line.split()
                    all_words += words
    
    dictionary = Counter(all_words)
    list_to_remove = list(dictionary.keys())
    for item in list_to_remove:
        if item.isalpha() == False:
            del dictionary[item]
        elif len(item) == 1:
            del dictionary[item]
    dictionary = dictionary.most_common(3000)
    return dictionary

In [44]:
dictionary = make_vocabulary(train_dir)

In [45]:
#Display modified 'dictionary'
dictionary

[('order', 1414),
 ('address', 1293),
 ('report', 1216),
 ('mail', 1127),
 ('send', 1079),
 ('language', 1072),
 ('email', 1051),
 ('program', 1001),
 ('our', 987),
 ('list', 935),
 ('one', 917),
 ('name', 878),
 ('receive', 826),
 ('money', 788),
 ('free', 762),
 ('work', 755),
 ('information', 677),
 ('business', 654),
 ('please', 652),
 ('university', 595),
 ('us', 564),
 ('day', 556),
 ('follow', 544),
 ('internet', 520),
 ('over', 511),
 ('http', 479),
 ('check', 472),
 ('call', 469),
 ('each', 466),
 ('include', 452),
 ('com', 448),
 ('linguistic', 442),
 ('number', 423),
 ('want', 420),
 ('letter', 419),
 ('need', 418),
 ('many', 412),
 ('here', 397),
 ('market', 395),
 ('start', 390),
 ('even', 386),
 ('fax', 383),
 ('form', 380),
 ('most', 377),
 ('first', 373),
 ('web', 366),
 ('service', 363),
 ('interest', 362),
 ('software', 352),
 ('remove', 349),
 ('read', 347),
 ('those', 345),
 ('week', 344),
 ('every', 332),
 ('credit', 329),
 ('ll', 326),
 ('site', 320),
 ('much', 31

In [46]:
#Assigning an index to words
vocab = {}
for i, (word, frequency) in enumerate(dictionary):
    vocab[word] = i

In [47]:
#View Indexing
vocab

{'order': 0,
 'address': 1,
 'report': 2,
 'mail': 3,
 'send': 4,
 'language': 5,
 'email': 6,
 'program': 7,
 'our': 8,
 'list': 9,
 'one': 10,
 'name': 11,
 'receive': 12,
 'money': 13,
 'free': 14,
 'work': 15,
 'information': 16,
 'business': 17,
 'please': 18,
 'university': 19,
 'us': 20,
 'day': 21,
 'follow': 22,
 'internet': 23,
 'over': 24,
 'http': 25,
 'check': 26,
 'call': 27,
 'each': 28,
 'include': 29,
 'com': 30,
 'linguistic': 31,
 'number': 32,
 'want': 33,
 'letter': 34,
 'need': 35,
 'many': 36,
 'here': 37,
 'market': 38,
 'start': 39,
 'even': 40,
 'fax': 41,
 'form': 42,
 'most': 43,
 'first': 44,
 'web': 45,
 'service': 46,
 'interest': 47,
 'software': 48,
 'remove': 49,
 'read': 50,
 'those': 51,
 'week': 52,
 'every': 53,
 'credit': 54,
 'll': 55,
 'site': 56,
 'much': 57,
 'english': 58,
 'edu': 59,
 'product': 60,
 'bulk': 61,
 'phone': 62,
 'must': 63,
 'two': 64,
 'offer': 65,
 'cost': 66,
 'best': 67,
 'www': 68,
 'computer': 69,
 'link': 70,
 'state': 

In [48]:
#FEATURE EXTRACTION
def features_extract(mail_dir, vocab):
    files = [os.path.join(mail_dir, fi) for fi in os.listdir(mail_dir)]
    files.sort()
    docId = 0
    matrix = np.zeros((len(files),3000))
    for file in files:
        with open(file) as m:
            for i, line in enumerate(m):
                if i==2:
                    words = line.split() 
                    wordId = 0
                    for word in words:
                        if word not in vocab.keys():
                            continue
                        wordId = vocab[word]
                        matrix[docId, wordId] = words.count(word)
            docId += 1
    
    return matrix

In [49]:
#making matrix of words
word_matrix = features_extract(train_dir, vocab)

In [50]:
#dispaly matrix shape
word_matrix.shape

(702, 3000)

In [51]:
# data = word_matrix
# scaler = StandardScaler()
# scaler.fit(data)
# word_matrix = scaler.transform(data)
# print(scaler.transform(data))

In [52]:
#TRAINING

train_labels = np.zeros(702)
train_labels[351:701] = 1

model1 = MultinomialNB() 
model2 = LinearSVC(C=0.01, class_weight=None, dual=False, fit_intercept=True,
           intercept_scaling=1, loss='squared_hinge', max_iter=100000,
           multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
           verbose=0)
model3 = LogisticRegression(C=1000, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

model3.fit(word_matrix,train_labels)
model4 = SVC()
model5 = RandomForestClassifier()
model6 = KNeighborsClassifier()

model1.fit(word_matrix,train_labels)
model2.fit(word_matrix,train_labels)
model3.fit(word_matrix,train_labels)
model4.fit(word_matrix,train_labels)
model5.fit(word_matrix,train_labels)
model6.fit(word_matrix,train_labels)

KNeighborsClassifier()

In [53]:
# TESTING
test_labels = np.zeros(260)
test_labels[130:260] = 1
test_word_matrix = features_extract(test_dir, vocab)

In [54]:
# data_test = test_word_matrix
# scaler = StandardScaler()
# scaler.fit(data_test)
# test_word_matrix = scaler.transform(data_test)
# print(scaler.transform(data_test))

In [55]:
result1 = model1.predict(test_word_matrix)
result2 = model2.predict(test_word_matrix)
result3 = model3.predict(test_word_matrix)
result4 = model4.predict(test_word_matrix)
result5 = model5.predict(test_word_matrix)
result6 = model6.predict(test_word_matrix)

In [56]:
 print(confusion_matrix(test_labels, result1))

[[129   1]
 [  9 121]]


In [57]:
 print("model1:",accuracy_score(test_labels,result1)*100,"%")

model1: 96.15384615384616 %


In [58]:
 result1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1.

In [59]:
print(confusion_matrix(test_labels, result2))

[[126   4]
 [  2 128]]


In [60]:
print("model2:",accuracy_score(test_labels,result2)*100,"%")

model2: 97.6923076923077 %


In [61]:
result2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [62]:
print(confusion_matrix(test_labels, result3))

[[126   4]
 [  1 129]]


In [63]:
print("model3:",accuracy_score(test_labels,result3)*100,"%")

model3: 98.07692307692307 %


In [64]:
result3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [65]:
print("model4:",accuracy_score(test_labels,result4)*100,"%")
print("model5:",accuracy_score(test_labels,result5)*100,"%")
print("model6:",accuracy_score(test_labels,result6)*100,"%")

model4: 90.38461538461539 %
model5: 96.92307692307692 %
model6: 93.07692307692308 %
